server:
  port: 9087
  
spring:
  application:
    name: pricing-svc
  cloud:
    config:
      uri: http://localhost:8888
  zipkin:
    base-url: http://localhost:9412/
  sleuth:
    sampler:
      probability: 1