server:
  port: 9412

spring:
  application:
    name: log-manage
  cloud:
    config:
      uri: http://localhost:8888
  sleuth:
    stream:
      enabled: true
  main:
    allow-bean-definition-overriding: true             
          
zipkin:
  storage:
    type: mem